include: _default_template.yaml
task: lvbench_documentary
dataset_name: lvbench_documentary
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: lvbench_documentary
    post_prompt: "Answer with the option's letter from the given choices directly."