include: _default_template.yaml
task: lvbench_tv
dataset_name: lvbench_tv
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: lvbench_tv
    post_prompt: "Answer with the option's letter from the given choices directly."