include: _default_template.yaml
task: lvbench_cartoon
dataset_name: lvbench_cartoon
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: lvbench_cartoon
    post_prompt: "Answer with the option's letter from the given choices directly."