dataset_path:  eval_data_jsons/Video-MME
dataset_kwargs:
  token: True
  cache_dir: your_eval_data_dir/VideoMME_0629
  video: True
  # From_YouTube: True
task: videomme_w_subtitle
test_split: test
output_type: generate_until
doc_to_visual: !function utils.videomme_doc_to_visual
doc_to_text: !function utils.videomme_doc_to_text_subtitle
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.videomme_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: videomme_percetion_score
    aggregation: !function utils.videomme_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    gemini_api_flag: "full subtitle"
  gemini_api:
    gemini_api_flag: "full subtitle"

metadata:
  - version: 0.0
