include: _default_template.yaml
task: mlvu_mc_topic_reasoning
dataset_name: 7_topic_reasoning
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: 7_topic_reasoning
    post_prompt: "Answer with the option's letter from the given choices directly."
  videochat_next_dynamic_newprompt:
    sub_task: 7_topic_reasoning
    yinan_prompt: "()"
    post_prompt: "\nOnly give the best option."
  videochat_next_dynamic_pdrop_newprompt:
    sub_task: 7_topic_reasoning
    yinan_prompt: "()"
    post_prompt: "\nOnly give the best option."