include: _default_template.yaml
task: mvbench_object_shuffle
dataset_name: object_shuffle
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: object_shuffle
    post_prompt: "\nOnly give the best option."
