include: _default_template.yaml
task: mvbench_action_localization
dataset_name: action_localization
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_localization
    post_prompt: "\nOnly give the best option."
