include: _default_template.yaml
task: mvbench_action_count
dataset_name: action_count
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_count
    post_prompt: "\nOnly give the best option."
