include: _default_template.yaml
task: mvbench_counterfactual_inference
dataset_name: counterfactual_inference
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: counterfactual_inference
    post_prompt: "\nOnly give the best option."
