include: _default_template.yaml
task: mvbench_unexpected_action
dataset_name: unexpected_action
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: unexpected_action
    post_prompt: "\nOnly give the best option."