include: _default_template.yaml
task: mvbench_episodic_reasoning
dataset_name: episodic_reasoning
test_split: train
doc_to_visual: !function utils.mvbench_frames_doc_to_visual
generation_kwargs:
  max_new_tokens: 16
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
  
lmms_eval_specific_kwargs:
  default:
    sub_task: episodic_reasoning
    post_prompt: "\nOnly give the best option."
