include: _default_template.yaml
task: mvbench_action_antonym
dataset_name: action_antonym
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_antonym
    post_prompt: "\nOnly give the best option."
